Repository spe-uob/HealthcareLake, pull requests merged in 2021-05, with the labels that each got.

#137 Requirements docs
  docs/portfolio_b.md
Labels: documentation

#139 Fixes #138
  .circleci/config.yml
  .terraform.lock.hcl
  infra/main.tf
  infra/modules/glue/iam.tf
  infra/modules/glue/main.tf
  infra/modules/glue/variables.tf
Labels: devops, infrastructure

#147 modified Personal Data, Privacy, Security and Ethics Management
  .terraform.lock.hcl
  docs/portfolio_b.md
Labels: documentation

#146 Docs/testing
  docs/portfolio_b.md
  main.tf
Labels: documentation

#148 added reflection
  docs/portfolio_b.md
Labels: documentation, help wanted

#150 Docs/acc testing
  docs/portfolio_b.md
Labels: documentation
